version: '2'
services:
  web:
      image: nginx:latest
      ports:
          - "8880:80"
      volumes:
          - .:/web
          - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      links:
          - php
  php:
      image: php:7.0.21-alpine
      volumes:
          - .:/web